### ISSUE TITLE
SelectBox: Label transition 

### ISSUE THREAD

**Issue by tomzaoral** [purple-technology/phoenix-components#21] opened 2020-02-24 13:55 UTC
### Description:
Label transition is too fast. 

### How to reproduce the issue:
Add onFocus event to props on SelectBox component

![bug_country](https://user-images.githubusercontent.com/1371109/75158048-a1e09080-5715-11ea-9ceb-4ef63802ba05.gif)

**Comment by brno32** [comment] 2020-03-18 21:18
I'm not able to reproduce. What's the behavior of your onFocus event?

**Comment by samuelg0rd0n** [comment] 2021-05-28 11:18
Will be fixed in the upcoming v4.

**Closed** 2021-06-15 11:19 UTC
Labels: bug
